export default function HomePage() {
  return (
    <div>
      <h1>Strona główna</h1>
      <ul>
        <li>Lorem.</li>
        <li>Minima?</li>
        <li>Quaerat!</li>
        <li>Tempore.</li>
        <li>Harum?</li>
        <li>Expedita.</li>
        <li>Rem.</li>
        <li>Ipsum.</li>
        <li>Adipisci.</li>
        <li>Voluptas!</li>
        <li>Molestiae!</li>
        <li>Odit.</li>
        <li>Ea.</li>
        <li>Voluptas?</li>
        <li>Tenetur!</li>
        <li>Culpa.</li>
        <li>Qui.</li>
        <li>Cumque.</li>
        <li>Doloribus.</li>
        <li>Veritatis?</li>
        <li>Eius?</li>
        <li>Incidunt!</li>
        <li>Excepturi.</li>
        <li>Ut?</li>
        <li>Cum!</li>
        <li>Ea.</li>
        <li>Obcaecati.</li>
        <li>Esse.</li>
        <li>Iusto.</li>
        <li>Esse.</li>
        <li>Assumenda.</li>
        <li>Possimus!</li>
        <li>Facilis.</li>
        <li>Iure?</li>
        <li>Tempore?</li>
        <li>Adipisci!</li>
        <li>Sapiente.</li>
        <li>Rerum.</li>
        <li>Eaque!</li>
        <li>Ullam!</li>
        <li>Cupiditate!</li>
        <li>Molestiae!</li>
        <li>Officiis?</li>
        <li>Vel.</li>
        <li>Reprehenderit.</li>
        <li>Inventore!</li>
        <li>Facilis?</li>
        <li>Repellat.</li>
        <li>Minus?</li>
        <li>Ipsa!</li>
        <li>Architecto.</li>
        <li>Provident.</li>
        <li>Repellat.</li>
        <li>Nesciunt!</li>
        <li>Eum?</li>
        <li>Impedit?</li>
        <li>Laboriosam.</li>
        <li>Eum?</li>
        <li>Culpa?</li>
        <li>Ducimus?</li>
        <li>Eveniet.</li>
        <li>Similique!</li>
        <li>Rem.</li>
        <li>Molestias.</li>
        <li>Nulla.</li>
        <li>Blanditiis.</li>
        <li>Sapiente?</li>
        <li>Repellat?</li>
        <li>Totam.</li>
        <li>Libero.</li>
        <li>Possimus.</li>
        <li>Possimus?</li>
        <li>Praesentium.</li>
        <li>Dolores!</li>
        <li>Rem.</li>
        <li>Repellat.</li>
        <li>Quia!</li>
        <li>Vitae?</li>
        <li>Beatae!</li>
        <li>Corrupti.</li>
        <li>Dolor!</li>
        <li>Laboriosam?</li>
        <li>Cupiditate!</li>
        <li>Quae.</li>
        <li>A.</li>
        <li>Doloribus.</li>
        <li>Itaque.</li>
        <li>Magnam!</li>
        <li>Eaque!</li>
        <li>Error?</li>
        <li>Animi.</li>
        <li>Fugiat.</li>
        <li>Excepturi?</li>
        <li>Veritatis.</li>
        <li>Fugiat!</li>
        <li>Tenetur?</li>
        <li>Iste.</li>
        <li>Rerum.</li>
        <li>Fugiat.</li>
        <li>Omnis!</li>
        <li>Distinctio.</li>
        <li>Sint.</li>
        <li>Beatae.</li>
        <li>Repellendus.</li>
        <li>Dolorem?</li>
        <li>Soluta.</li>
        <li>Adipisci!</li>
        <li>Eaque!</li>
        <li>Quo?</li>
        <li>Quasi!</li>
        <li>Tenetur?</li>
        <li>Error!</li>
        <li>Molestiae!</li>
        <li>Deserunt?</li>
        <li>Molestias!</li>
        <li>Nam.</li>
        <li>Commodi?</li>
        <li>Cumque?</li>
        <li>Similique!</li>
        <li>Aspernatur?</li>
        <li>Soluta.</li>
        <li>Suscipit?</li>
        <li>Nesciunt.</li>
        <li>Voluptates!</li>
        <li>Nobis?</li>
        <li>Ad.</li>
        <li>Perspiciatis!</li>
        <li>Aut.</li>
        <li>Nesciunt?</li>
        <li>Repellat?</li>
        <li>Omnis.</li>
        <li>Totam?</li>
        <li>Rerum?</li>
        <li>Id.</li>
        <li>Dolorum.</li>
        <li>Cupiditate?</li>
        <li>Aspernatur.</li>
        <li>Enim?</li>
        <li>Quos.</li>
        <li>Molestiae!</li>
        <li>Nobis!</li>
        <li>Similique!</li>
        <li>Dolore.</li>
        <li>Optio.</li>
        <li>Tempore.</li>
        <li>Voluptas!</li>
        <li>Quasi.</li>
        <li>Dolor.</li>
        <li>Sunt!</li>
        <li>Saepe.</li>
        <li>Voluptate.</li>
        <li>Explicabo!</li>
        <li>Dolores.</li>
        <li>Debitis?</li>
        <li>Velit?</li>
      </ul>
    </div>
  );
}
