import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/css/Globals.css";
import { Navigation } from "@/layout/Navigation";
import GET_MAIN_NAVIGATION from "@/data/queries/GET_MAIN_NAVIGATION";
import { MenuProvider } from "@/provider";

const inter = Inter({
  subsets: ["latin", "latin-ext"]
});

export const metadata: Metadata = {
  title: "LifeStylee",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menu = await GET_MAIN_NAVIGATION();

  return (
    <html lang="pl_PL">
      <MenuProvider>
        <body className={`${inter.className} antialiased`}>
          <Navigation menu={menu} />
          {children}
        </body>
      </MenuProvider>
    </html>
  );
}
