import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/css/Globals.css";
import { Navigation } from "@/layout/Navigation";
import GET_MAIN_NAVIGATION from "@/data/queries/GET_MAIN_NAVIGATION";
import { MenuProvider } from "@/provider";
import Script from "next/script";
import Clarity from '@microsoft/clarity';


const inter = Inter({
  subsets: ["latin", "latin-ext"]
});

export const metadata: Metadata = {
  title: "LifeStylee",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menu = await GET_MAIN_NAVIGATION();


  return (
    <html lang="pl_PL">
      <head>
        <link rel="canonical" href="" />
        <meta name="google-site-verification" content="Ff8M9SgTYgIi3oyAqDXMx1nZOJsOzMLLQBE3dEB1sPc" />
        <Script
          id="gtm-script"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;
              j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;
              f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','GTM-5J59KVQ2');
            `,
          }}
        />
      </head>
      <MenuProvider>
        <body className={`${inter.className} antialiased`}>
          <noscript>
            <iframe
              src="https://www.googletagmanager.com/ns.html?id=GTM-5J59KVQ2"
              height="0"
              width="0"
              style={{ display: "none", visibility: "hidden" }}
            ></iframe>
          </noscript>
          <Navigation menu={menu} />
          {children}
        </body>
      </MenuProvider>
    </html>
  );
}
