import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "@/css/global.scss";
// import GET_POSTS from "@/data/graphql/GET_POSTS";
import { Subdomains } from "@/nav/index";
import GET_SUBDOMAINS from "@/queries/GET_SUBDOMAINS";

const OpenSans = Open_Sans({
  variable: "--font-regular",
  subsets: ["latin", "latin-ext"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { subdomains } = await GET_SUBDOMAINS();

  return (
    <html lang="en">
      <body className={`${OpenSans.variable}`}>
        <Subdomains subdomains={subdomains} />
        {children}
      </body>
    </html>
  );
}
