import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/css/global.css";
import GET_POSTS from "@/data/graphql/GET_POSTS";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { posts } = await GET_POSTS();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {posts.map((item) => {
          return (
            <li key={item.title}>
              <figure>
                <Image
                  alt={item.image.altText}
                  height={250}
                  src={item.image.sourceUrl}
                  width={250}
                />
              </figure>
              <h3>{item.title}</h3>
            </li>
          );
        })}
        {children}
      </body>
    </html>
  );
}
