import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <menu>
          <li>Technologie</li>
          <li>Newsy</li>
          <li>Zdrowie</li>
          <li>Beauty</li>
          <li>Rolnictwo</li>
          <li>Budownictwo</li>
          <li>E-commerce</li>
          <li>Biznes</li>
          <li>Psychologia</li>
          <li>Religia</li>
          <li>Sport</li>
          <li>Kultura</li>
        </menu>
        <nav>
          <div>LifeStylee</div>
          <menu>
            <li>
              <p>Technologia</p>
              <ul>
                <li>Elektronika</li>
                <li>Sztuczna inteligencja</li>
                <li>Programowanie</li>
                <li>IoT</li>
                <li>Gadżety</li>
                <li>Open Source</li>
                <li>Robotyka</li>
                <li>Systemy operacyjne</li>
                <li>Apple</li>
                <li>Kosmos</li>
                <li>Druk 3D</li>
                <li>Fotografie</li>
                <li>Automatyzacje</li>
                <li>VR</li>
                <li>Infreastruktura IT</li>
              </ul>
            </li>
            <li>
              <p></p>
              <ul>
                <li></li>
              </ul>
            </li>
            <li>
              <p></p>
              <ul>
                <li></li>
              </ul>
            </li>
            <li>
              <p></p>
              <ul>
                <li></li>
              </ul>
            </li>
          </menu>
          <form className="" action="" method="">
            <input type="search" className="" />
            <button>szukaj</button>
          </form>
        </nav>
        {children}
      </body>
    </html>
  );
}
