import main from "@/data/main";
import { subdomains } from "@/data/subdomains";
import { rewrites } from "@/lib/configs/rewrites";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // console.log("rewrites: ", rewrites);
  // console.log("subdomains: ", subdomains);
  const domains = subdomains.map((subdomain) => subdomain.url.split(".")[0]);
  // console.log(domains);
  return (
    <html lang="pl_PL">
      <body>
        <menu>
          {main.subdomains.map((item) => {
            return (
              <Link
                style={{
                  backgroundColor: item.color.background,
                  color: item.color.foreground,
                }}
                href={item.url}
                key={item.title}
                {...item.props}
              >
                {item.title}
              </Link>
            );
          })}
        </menu>
        <nav>
          <div>LifeStylee</div>
          <menu>
            <li>
              <p>Technologia</p>
              <ul>
                <li>Elektronika</li>
                <li>Sztuczna inteligencja</li>
                <li>Programowanie</li>
                <li>IoT</li>
                <li>Gadżety</li>
                <li>Open Source</li>
                <li>Robotyka</li>
                <li>Systemy operacyjne</li>
                <li>Apple</li>
                <li>Kosmos</li>
                <li>Druk 3D</li>
                <li>Fotografie</li>
                <li>Automatyzacje</li>
                <li>VR</li>
                <li>Infreastruktura IT</li>
              </ul>
            </li>
            <li>
              <p></p>
              <ul>
                <li></li>
              </ul>
            </li>
            <li>
              <p></p>
              <ul>
                <li></li>
              </ul>
            </li>
            <li>
              <p></p>
              <ul>
                <li></li>
              </ul>
            </li>
          </menu>
          <form className="" action="" method="">
            <input type="search" className="" />
            <button>szukaj</button>
          </form>
        </nav>
        {children}
      </body>
    </html>
  );
}
