import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@/css/global.scss";
import { Navigation } from "@/layout/index";
import main from "@/static/main";

const montserrat = Montserrat({
  variable: "--font-regular",
  subsets: ["latin", "latin-ext"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable}`}>
        <Navigation {...main.nav} />
        {children}
      </body>
    </html>
  );
}
