import type { Metadata } from "next";
import { Alegreya, Open_Sans } from "next/font/google";
import "@/css/global.scss";
import { Navigation } from "@/layout/index";
import main from "@/static/main";
import { MenuProvider } from "@/provider/index";

const alegreya = Alegreya({
  preload: true,
  variable: "--font-alegreya",
  subsets: ["latin", "latin-ext"],
});

const openSans = Open_Sans({
  variable: "--font-openSans",
  subsets: ["latin", "latin-ext"],
  preload: true,
  weight: ["300", "400", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${alegreya.variable} ${openSans.variable}`}>
        <MenuProvider>
          <Navigation {...main.nav} />
          {children}
        </MenuProvider>
      </body>
    </html>
  );
}
