import type { Metadata } from "next";
import "@/styles/globals.css";
import { inter, lora } from "@/assets/fonts/Fonts";
import { Navigation } from "@/components/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl_PL">
      <body className={`${inter.variable} ${lora.variable} antialiased`}>
        <Navigation />
        <div className="ml-64 flex-1 p-5">{children}</div>
      </body>
    </html>
  );
}
