import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "@/css/global.scss";
import { Navigation } from "@/layout/Navigation/index";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin", "latin-ext"],
  preload: true
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl_PL">
      <body className={`${lexend.variable}`}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
